cliDefaults:
  run:
    sequential: true
excludes:
  - '**/.tsbuild/**'
  - '**/generated/**'
  - '**/node_modules/**'
  - package-lock.json
  - services/activecampaign/src/openapi.json
includes:
  - services/**
outputPath: .stan
patchOpenCommand: code -g {file}
scripts:
  knip: npm run knip
  typecheck: npm run typecheck
  lint: npm run lint
  openapi: npm run openapi
  test: npm run test
  package: npm run package
stanPath: .stan

