/**
 * This script generates an OpenAPI 3.1.0 specification document for the API.
 *
 * It uses the `zod-openapi` library to create the document from JSDoc-annotated
 * Zod schemas. The generated document is written to `src/openapi/openapi.json`.
 *
 * @see https://github.com/johngalt/zod-openapi */
// Load side-effect registrations generated by the CLI
import * as __register_openapi from '@/app/generated/register.openapi';
void __register_openapi;

import fs from 'fs-extra';
import { packageDirectorySync } from 'package-directory';
import path from 'path';
import { createDocument } from 'zod-openapi';

import { app } from '@/app/config/app.config';
console.log('Generating OpenAPI document...');
/**
 * The OpenAPI document object. *
 * @see https://spec.openapis.org/oas/v3.1.0
 */
const paths = app.buildAllOpenApiPaths();
export const doc = createDocument({
  openapi: '3.1.0',
  servers: [
    { description: 'Production', url: 'https://api.example.test' },
    { description: 'Dev', url: 'https://api.dev.example.test' },
  ],
  info: {
    // Read the package name and version from `package.json` via environment variables.
    title: process.env.npm_package_name ?? '',
    version: process.env.npm_package_version ?? '',
  },
  paths,
});

/**
 * The root directory of the package.
 */
const pkgDir = packageDirectorySync();
if (!pkgDir) throw new Error('Could not find package root directory');

// Write the generated OpenAPI document to `app/generated/openapi.json`.
const outDir = path.join(pkgDir, 'app', 'generated');
fs.ensureDirSync(outDir);
fs.writeFileSync(
  path.join(outDir, 'openapi.json'),
  JSON.stringify(doc, null, 2),
);

console.log('Done!');
