name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
      - name: Install
        run: npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Package
        run: npm run package
