name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
      - name: Prepare npm (pin version, registry, retries)
        run: |
          npm i -g npm@10.9.0
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 10000
          npm config set fetch-retry-maxtimeout 120000
          npm --version
          npm config get registry
          npm config get fetch-retries
      - name: Install
        run: npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
